[metadata.heroku]
  root-package = "github.com/emojitracker/emojitrack-gostreamer"
  go-version = "1.10"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mroth/sseserver"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gomodule/redigo"
  version = "2.0.0"

[[constraint]]
  name = "github.com/yvasiyarov/gorelic"
  revision = "3bb8f36985b980550ccad08dffee4d1a1441817b"
